"""fix some bugs that occured in tasks model

Revision ID: 2bc920466fb4
Revises: cc28f9b19980
Create Date: 2026-07-04 11:05:42.265786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc920466fb4'
down_revision: Union[str, Sequence[str], None] = 'cc28f9b19980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('board_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'board_id')
    # ### end Alembic commands ###
