"""Initial migration

Revision ID: 42f2b9a26388
Revises:
Create Date: 2026-07-21 15:22:08.199415

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "42f2b9a26388"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
